name = "ClearStacktrace"
uuid = "710b7bb7-6527-48f4-8ff2-df22ae1c6308"
authors = ["Julius Krumbiegel"]
version = "0.2.1"

[deps]

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
